# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bout_end <- function(seq, activity, interval, size, window_size) {
    .Call('_activPAL_bout_end', PACKAGE = 'activPAL', seq, activity, interval, size, window_size)
}

